### ISSUE TITLE
so how to use it... is this still work?

### ISSUE THREAD

**Issue by dhana-exe** [dev-coco/Classic-Facebook#1]
is this still work?
all fb extension broken

**Comment by dev-coco** [comment]
This is still available, you can try it. Because the method used by this
extension is a very old User-Agent instead of using the group's API
interface.

dhanamerdeka <notifications@github.com> 于2020年12月5日周六 上午11:10写道：

**Comment by dev-coco** [comment]
This is still available, you can try it. Because the method used by this
extension is a very old User-Agent instead of using the group's API
interface.

**Comment by dev-coco** [comment]
After installing the extension, click on the extension and select the first button. The first button is to return to the old version, and the second button is to return to the new version.

**Comment by dhana-exe** [comment]
ah yeah....
i tested few second ago...
and yeah....
app broke like another app....
i'ts keep redirecting without stopped....
i hope you can find another way to deal with fb shitty theme

**Comment by dev-coco** [comment]
Try a new one, but it can't be used on the homepage. I have no idea for the that, but it can be used normally in the timeline and group.

**Comment by dhana-exe** [comment]
are you want to make something like.... custom skinning for facebook?
so they can still shown as old facebook while we get data from new ones....?

**Comment by dev-coco** [comment]
I did not consider making a custom Facebook skin appearance, because there is too much CSS work to do, compatibility and so on need to be considered.

**Comment by dhana-exe** [comment]
ahhh i see....
so yeah.... the fb old layout now died....
:) thanks
